export const allProducts = {
  "women-clothes": [
    {
      id: "w1",
      name: "Amina Kedir",
      artisan: "Artisan Weaver",
      price: 4500,
      originalPrice: 6458,
      image: "/images/dress.jpg",
      category: "women-clothes",
      description: "Beautiful traditional women's dress with intricate embroidery",
      rating: 4.5,
      reviews: 12,
    },
    {
      id: "w2",
      name: "Hana Badege",
      artisan: "Artisan Weaver",
      price: 5000,
      originalPrice: 6700,
      image: "/images/dress2.jpg",
      category: "women-clothes",
      description: "Elegant traditional dress perfect for special occasions",
      rating: 4.8,
      reviews: 18,
    },
    {
      id: "w3",
      name: "Sitra Taha",
      artisan: "Artisan Weaver",
      price: 5300,
      originalPrice: 5700,
      image: "/images/dress3.jpg",
      category: "women-clothes",
      description: "Premium quality traditional women's garment",
      rating: 4.6,
      reviews: 15,
    },
    {
      id: "w4",
      name: "Alem Zewdu",
      artisan: "Artisan Weaver",
      price: 3000,
      originalPrice: 4500,
      image: "/images/dress4.jpg",
      category: "women-clothes",
      description: "Affordable traditional dress for everyday wear",
      rating: 4.3,
      reviews: 8,
    },
    {
      id: "w5",
      name: "Beza Alemayehu",
      artisan: "Artisan Weaver",
      price: 4000,
      originalPrice: 5700,
      image: "/images/dress5.jpg",
      category: "women-clothes",
      description: "Stylish traditional women's outfit",
      rating: 4.7,
      reviews: 14,
    },
    {
      id: "w6",
      name: "Lily Tadesse",
      artisan: "Artisan Weaver",
      price: 5000,
      originalPrice: 6000,
      image: "/images/dress6.jpg",
      category: "women-clothes",
      description: "Exquisite handmade traditional dress",
      rating: 4.9,
      reviews: 22,
    },
  ],
  "men-clothes": [
    {
      id: "m1",
      name: "Kedija Mohammed",
      artisan: "Artisan Weaver",
      price: 3700,
      originalPrice: 5000,
      image: "/images/men.jpg",
      category: "men-clothes",
      description: "Traditional men's outfit with classic design",
      rating: 4.4,
      reviews: 10,
    },
    {
      id: "m2",
      name: "Hana Badege",
      artisan: "Artisan Weaver",
      price: 4900,
      originalPrice: 5700,
      image: "/images/men1.jpg",
      category: "men-clothes",
      description: "Premium men's traditional garment",
      rating: 4.6,
      reviews: 13,
    },
    {
      id: "m3",
      name: "Selam Kebede",
      artisan: "Artisan Weaver",
      price: 3200,
      originalPrice: 4100,
      image: "/images/men.jpg",
      category: "men-clothes",
      description: "Comfortable traditional men's wear",
      rating: 4.2,
      reviews: 7,
    },
    {
      id: "m4",
      name: "Amina Kedir",
      artisan: "Artisan Weaver",
      price: 5090,
      originalPrice: 6100,
      image: "/images/men3.png",
      category: "men-clothes",
      description: "Elegant traditional men's outfit",
      rating: 4.8,
      reviews: 19,
    },
    {
      id: "m5",
      name: "Zeritu Mulugeta",
      artisan: "Artisan Weaver",
      price: 3800,
      originalPrice: 5900,
      image: "/images/men4.jpg",
      category: "men-clothes",
      description: "Stylish men's traditional dress",
      rating: 4.5,
      reviews: 11,
    },
    {
      id: "m6",
      name: "Helina Assefa",
      artisan: "Artisan Weaver",
      price: 5200,
      originalPrice: 6400,
      image: "/images/menn.jpg",
      category: "men-clothes",
      description: "Premium quality men's garment",
      rating: 4.7,
      reviews: 16,
    },
  ],
  jewelry: [
    {
      id: "j1",
      name: "Amina Kedir",
      artisan: "Artisan Weaver",
      price: 425,
      originalPrice: 500,
      image: "/images/rings.png",
      category: "jewelry",
      description: "Beautiful silver jewelry set",
      rating: 4.5,
      reviews: 9,
    },
    {
      id: "j2",
      name: "Kalkidan Gebre",
      artisan: "Artisan Weaver",
      price: 608,
      originalPrice: 778,
      image: "/images/rings2.jpg",
      category: "jewelry",
      description: "Elegant traditional jewelry",
      rating: 4.7,
      reviews: 14,
    },
    {
      id: "j3",
      name: "Sumeya Sadik",
      artisan: "Artisan Weaver",
      price: 200,
      originalPrice: 140,
      image: "/images/rings3.jpg",
      category: "jewelry",
      description: "Handcrafted jewelry collection",
      rating: 4.4,
      reviews: 8,
    },
    {
      id: "j4",
      name: "Hermella Kassahun",
      artisan: "Artisan Weaver",
      price: 100,
      originalPrice: 50,
      image: "/images/rings4.jpg",
      category: "jewelry",
      description: "Artisan silver rings",
      rating: 4.6,
      reviews: 12,
    },
  ],
  gabi: [
    {
      id: "g1",
      name: "Traditional Gabi",
      artisan: "Lily Tadesse",
      price: 5000,
      originalPrice: 10000,
      image: "/images/gabi.jpg",
      category: "gabi",
      description: "Premium traditional gabi wrap",
      rating: 4.8,
      reviews: 20,
    },
    {
      id: "g2",
      name: "Elegant Gabi",
      artisan: "Lily Tadesse",
      price: 4500,
      originalPrice: 8000,
      image: "/images/gabi2.jpg",
      category: "gabi",
      description: "Beautiful handmade gabi",
      rating: 4.7,
      reviews: 17,
    },
    {
      id: "g3",
      name: "Classic Gabi",
      artisan: "Lily Tadesse",
      price: 3500,
      originalPrice: 6000,
      image: "/images/gabi00.jpg",
      category: "gabi",
      description: "Traditional gabi for everyday wear",
      rating: 4.5,
      reviews: 11,
    },
    {
      id: "g4",
      name: "Premium Gabi",
      artisan: "Lily Tadesse",
      price: 6000,
      originalPrice: 12000,
      image: "/images/gabi0.jpg",
      category: "gabi",
      description: "Luxury traditional gabi wrap",
      rating: 4.9,
      reviews: 25,
    },
  ],
}

export function getProductById(id: string) {
  for (const category in allProducts) {
    const product = allProducts[category as keyof typeof allProducts].find((p) => p.id === id)
    if (product) return product
  }
  return null
}

export function getProductsByCategory(category: string) {
  return allProducts[category as keyof typeof allProducts] || []
}
